<?php
include "include/base_includes.php";
include "include/view/layout.php";
?>
<!DOCTYPE html>
<html lang="en">
<?php
AddGenericHead();

AddHeader_StartMain(GetNavLinks());
?>

<div class="row"><h1 class="header">Legals</h1>
    <div class="singleColumn">
    <div class="card clearfix">
        <p><strong>Only financial  members will be granted access to this site and given access to the booking  facility.</strong></p>
        <p><strong>All bookings require  that the member and/or member's partner/spouse are in residence during the  booking. Eviction can result if the member has booked the unit and permits  someone other than the member and/or member's partner/spouse to use the unit  when not accompanied by the member and/or member's partner/spouse.</strong></p>
        <p>When booking accommodation online through <a href="https://www.cpefs.com.au">www.cpefs.com.au</a> ("CPEFS") you ("the Customer") agree to the following terms and conditions:</p>
        <ol>
            <li>
                <strong>Administration Fees<br>
                </strong> An administration fee of $30.00 (included in the rental charges) applies to all bookings,
                booking changes and cancellations.&nbsp; The administration charge must be paid 30 days prior to
                occupancy.&nbsp; Failure to pay the complete rental fees 30 days prior to occupancy will result in loss
                of booking and forfeiture of the administration fee.
            </li>
            <li>
                <strong>Deposit</strong><br>
                A deposit of $100.00 per week per booking, calculated on the number of weeks booked, applies and must be
                paid within 10 days of booking the accommodation.&nbsp; Failure to pay the deposit within the specified
                time will result in automatic cancellation of booking and forfeiture of the administration fee.
            </li>
            <li>
                <strong>Cancellation</strong><br>
                If any accommodation booking is cancelled less than 30 days from the booking then that cancellation will
                result in forfeiture of the deposit and the administration fee paid.
            </li>
            <li>
                <strong>Payment</strong><br>
                To cover any incidental costs incurred by CPEFS as a result of the booking or cancellation of the
                booking, at the time of booking the accommodation, the Customer will be required to provide particulars
                of a current credit card in the name of the Customer.&nbsp; The Customer will be required to provide
                photo ID at the time of check in.
            </li>
            <li>
                <strong>Wilful and other damage</strong><br>
                The Customer will be evicted from the premises if it engages in untoward behaviour.&nbsp; If the
                Customer is evicted from the premises due to untoward behaviour the full accommodation fee will be
                charged and no refund will be given to the Customer.&nbsp; The term &quot;untoward behaviour&quot;
                includes but is not limited to negligent acts, theft, wilful damage, excessive noise, failing to keep
                the premises in a clean and tidy state, failing to keep any area of the common property that the
                Customer uses in a clean and tidy state and behaviour affecting the peaceful enjoyment by other
                Customers, and shall be determined by the Manager and at the Manager's discretion.
            </li>
            <li>
                <strong>Charges Payable by the Customer</strong><br>

                In addition to the accommodation and administration fees, the Customer will be responsible for payment
                of the following items -
                <ol>
                    <li> The full replacement costs of any items or property which is broken or removed from the
                        premises or the common property of the building by the Customer or any person associated with,
                        or invited onto the property by, the Customer.
                    </li>
                    <li> Any excess cleaning charges which are incurred by CPEFS.</li>
                    <li> Any telephone calls or internet connection fees generated by the Customer.</li>
                    <li> Any additional laundering fees incurred by CPEFS for additional linen used by the Customer.
                    </li>
                    <li> A linen rental fee for additional linen arranged by the Customer.</li>
                    <li> Any entertainment costs incurred by the customer for &quot;in house&quot; entertainment
                        services ordered by the Customer.
                    </li>
                    <li> Any other costs or expenses incurred by CPEFS as a result of the Customer&rsquo;s occupancy of
                        the property.
                    </li>
                </ol>
            </li>
            <li>
                <strong>Disclaimer</strong>
                <ol>
                    <li> CPEFS makes its best efforts to ensure that the information available on its website is
                        accurate. However, CPEFS cannot and does not guarantee that the site is free from errors or
                        faults.
                    </li>
                    <li> CPEFS does not accept liability for any errors or omissions and reserves the right to change
                        information published on the site at any time.
                    </li>
                    <li> CPEFS does not accept liability for any indirect or consequential loss arising out of the use
                        of or connected with its website or for any products or services purchased from its website.
                    </li>
                    <li> CPEFS makes no warranty or representation about the fitness or suitability of any product or
                        service advertised on its website.
                    </li>
                    <li> CPEFS offers are not commissionable to registered travel agents.</li>
                    <li> You must be at least 18 years of age to book units on <a href="https://www.cpefs.com.au">www.cpefs.com.au</a>
                    </li>
                </ol>
            </li>
            <li>
                <strong>Statutory Rights<br>
                </strong> These terms do not affect consumers' statutory rights.
            </li>
            <li><strong>Indemnity</strong><br>
                The Customer indemnifies CPEFS in respect of any loss or damage suffered by CPEFS as a result of the
                Customer&rsquo;s occupation of the premises.
            </li>
        </ol>
</div>
    </div>
</div>

    <?php
    AddFooter_CloseMain();
    ?>
</html>